name: Rehash Assets
on: 
  push:
    branches:
      - cn
  workflow_dispatch:

permission:
  write

jobs:
  generate:
    name: Rehash Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
            python-version: '3.10'
      - name: Checkout ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Hash asset.json
        run: python hash.py
      - name: Commit files
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Rehash Assets"
      - name: Push changes
        continue-on-error: false
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}